services:

  iron-x-iris:
    image: cert-edf/iron-x-iris
    ports:
      - 8080:8080
    volumes:
      - /data/iron_x_iris/conf:/conf
      - /data/iron_x_iris/data:/data
    environment:
      ROLE: proxy
      FUSION_DEBUG: 0
